# Generated by Django 3.0.4 on 2020-11-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Number not detected', max_length=50)),
                ('faults', models.IntegerField(default=0)),
                ('fault1', models.CharField(default='No fault', max_length=50)),
                ('fault2', models.CharField(default='No fault', max_length=50)),
                ('fault3', models.CharField(default='No fault', max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
