# Generated by Django 3.0.4 on 2020-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='videofile',
            field=models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
