# Generated by Django 3.0.4 on 2020-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201118_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='numberofframes',
            field=models.IntegerField(default=0),
        ),
    ]
