# Generated by Django 3.0.4 on 2020-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_upload_numberofframes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='fault1',
            new_name='fault',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='number',
            new_name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='fault2',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='fault3',
        ),
        migrations.AddField(
            model_name='challan',
            name='frame_num',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
