# Generated by Django 3.0.4 on 2020-11-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201124_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='challan',
            new_name='gen_challan',
        ),
    ]
