# Generated by Django 3.0.4 on 2020-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201124_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='gen_challan',
            name='res_img',
            field=models.ImageField(blank=True, null=True, upload_to='deploy/videos/%Y/%m/%d/'),
        ),
    ]
