# Generated by Django 3.0.4 on 2020-11-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gen_challan_res_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gen_challan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
